### ISSUE TITLE
Cannot read property 'title' of undefined  (bit-docs-generate-html/build/make_default_helpers)

### ISSUE THREAD

**Issue by leoj3n** [bit-docs/bit-docs-website#10]
If you clone this repo (`bit-docs/bit-docs-website`) and remove the [postinstall script](https://github.com/bit-docs/bit-docs-website/blob/866aa43358d68a58583417e2d6a9a753e072a42b/package.json#L28) from `package.json` before running `npm install && npm run gen`, the following error happens:

```
npm info ok
PROCESSING: docs/bit-docs/contributing.md
PROCESSING: docs/bit-docs/plugins.md
PROCESSING: docs/bit-docs/guides.md
PROCESSING: docs/bit-docs/high-level-overview.md
BUILD: Copying templates from /Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-js/templates
BUILD: Installing packages
OUT: gh-pages/contributing.html
/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/q/q.js:126
                    throw e;
                    ^

TypeError: Cannot read property 'title' of undefined
    at Object.getTitle (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/build/make_default_helpers.js:396:16)
    at Object.eval (eval at createFunctionContext (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:40:52)
    at /Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/handlebars/dist/cjs/handlebars/runtime.js:86:31
    at /Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:465:21
    at renderer (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/build/get_renderer.js:24:11)
    at module.exports (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/write/doc_object.js:44:14)
    at Object.module.exports [as docMap] (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/write/doc_map.js:30:18)
    at /Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/bit-docs-generate-html/generate.js:64:16
    at _fulfilled (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/leoj/bitovi/+/bd/gm2/bit-docs-website/node_modules/bit-docs/lib/configure/node_modules/q/q.js:883:30)

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/leoj/.nvm/versions/node/v6.10.0/bin/node" "/Users/leoj/.nvm/versions/node/v6.10.0/bin/npm" "run" "gen"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bit-docs-website@0.0.1 gen: `bit-docs -d`
npm ERR! Exit status 1
```

I'm not sure why. Here is the code near where that throw happens:

```js
		/**
		* @function documentjs.generators.html.defaultHelpers.makeParentTitle
		*
		* Returns the parent docObject's title.
		*
		*/
		getTitle: function(){
			var root = docMap[config.parent];
			return (root.title || root.name)+ " - "+(this.title || this.name);
		},
```

Once all the `docs/modules/*` directories are all populated by submodule init the error subsides.

This is an error that I have sporadically encountered a number of times while setting up this repo, so I'm mostly just curious as to why it happens, and if it's something that can be handled perhaps in the `getTitle` function?

**Comment by leoj3n** [comment]
This happens in this instance because [BitDocs.md](https://github.com/bit-docs/bit-docs/blob/85db64893741a09ffc91e72cf110c393272aaa62/docs/BitDocs.md) needs to be present in the glob search and is not until `bit-docs` is cloned down as a submodule.
